### ISSUE TITLE
Option values not being saved

### ISSUE THREAD

**Issue by brennanbrown** [kenzan100/beeminder-obsidian-word-count#1]
I've encountered this bug on the Windows version of Obsidian, version 0.12.3:

After installing the plug-in, when adding the user values for it in options (auth_token, name, goal), the values disappear instantly after switching to another tab in the settings, and render the plug-in unusable. 

Trying to manually install it in my vault had the same effect.

**Comment by brennanbrown** [comment]
After looking at the `data.json`, it looks as though the values are saved and the plug-in works as intended, so my apologies there. It seems like this is just a cosmetic issue.

**Comment by kenzan100** [comment]
Thx for the report!
As you're kind enough to followup, the values are kept even after they're emptied from the config UI.

I'll work on providing more indications of the current values (maybe '****' for sensitive values) in spare time.
Happy to accept PRs as well 😃
